### ISSUE TITLE
Plugin Conflict with Woocommerce?

### ISSUE THREAD

**Issue by bugbee** [wp-cloud/wpmu-plugin-manager#2]
With WPMU Plugin Manger activated, one of my sites (the only one running Woocommerce) lost access to the admin area and we found an error log:

PHP Fatal error: Call to undefined function wp_get_current_user() in ../../wp-includes/capabilities.php on line 1342

This conflict disabled the ability for a customer to enter their credit card information. The front end of the site was functional otherwise.

As soon as i disabled WPMU Plugin Manager everything was restored on the shop and the admin area was for this site was available again.

Let me know if you need any other information.

**Comment by cfoellmann** [comment]
I am not sure it is a problem with WPMU Plugin Manager. There might be some capability issues within your installation.

**Comment by cfoellmann** [comment]
close for now
