### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by leedman** [wp-cloud/wpmu-plugin-manager#3]
I'm running a multisite and I had been having some speed issues. A support person dialed in to assist and deactivated all the plugins on the multisite by moving the folder of plugins out of wp-content. Ouch... not my way to do things.

Now I don't know if this is typical behavior - this is the first I came across it myself. Even though all the plugins were deactivated/broken/gone - there were functions still running due to those plugins. 

Example: JetPack got installed and one of the components alarms you via email when the site goes down. Well, with all these issues the site was going up and down frequently and I was getting emails alerting me of the fact even though the plugin/feature were gone from wp-content. 

Fast-forward, all this caused massive pain as the site remained down for days. Pulling the plugins folder out caused more problems than it solved. After much effort, the site came back and I was able to start slowly moving forward again, slowly troubleshooting.

Well, now I've got things running alright but I still get warnings and errors - misconfigurations, and the site is very very slow. So a friend of mine helped me out tonight and upon registering she received 2 activation emails, one from the updated admin email, another from an older admin email of mine. Again, pointing to old plugin data and service somehow being run.

First, have you ever heard such a thing before? And more importantly, could you have your plugin for managing plugins also evaluate what left over pieces are still in the database from uninstalled plugins? And I can't help wonder about background cron jobs possibly still in action, too.

**Comment by cfoellmann** [comment]
First: you should have reset to a backup after encountering these massive problems. Just a tip.
- I am not familiar with Jetpack but these mail notifications must come from the WP.com infrastructure. So it is normal for the service to notify you if some endpoint of your site that is used for these checks is not reachable. Only a proper deactivation of this function might work there.
- I have not heard of these problems but I am not surprised. It think it is a problem of some of the used plugins not following best practices.
- this plugin is pretty simple in how it works
  So there is room for improvement.

I will get back to this Plugin soon. Let me know of a specific idea we can talk about

**Comment by leedman** [comment]
Yep, I should have been a little tougher, too. He took over far too
quickly. :)

Oh well, we learn and live.

I have been digging all day into this situation and came across other
plugins that let you see all the options in the database. As you know,
plugins and other modules can consist of many elements when you're looking
at all these coded options in a very straight forward list.

The issue here is how to protect noobs - and even power users like me - who
know enough not to go messing with that stuff, but when it comes right down
to a last ditch attempt at salvaging an installation setup, you will go and
push some buttons.

How can one recognize which elements added to the database belong to a
non-installed plugin and provides the option to delete all it's data?
Essentially a mini-reset.

Lee Down

778-862-1626

_OMC Social Media Promotions_
omcsocial.com

Art Promotion Project,
*Arts, Artists, Artwork *
artsartistsartwork.com

http://www.dreamhost.com/r.cgi?391391/green.cgi?ArtsArtistsArtwork%7CHELPHOSTAAA
_Get Green Hosting by
Dreamhost_http://www.dreamhost.com/r.cgi?391391/green.cgi?ArtsArtistsArtwork%7CHELPHOSTAAA,
they are the hosting provider for Arts, Artists,
Artworkhttp://artsartistsartwork.com,
also fondly known as _AAA_ https://www.facebook.com/artsartistsartwork.
You can donate and help provide for service costs in support of the Arts
Community Worldwide. Currently hosted on a Virtual Private Server,
performance issues and slow site speed has been increasing in frequency.
VPS Cloud Hosting is an option currently being evaluated, wanting to
provide a stronger platform and faster speed to help grow the site. It
might even save us money.

**Comment by cfoellmann** [comment]
`How can one recognize which elements added to the database belong to a non-installed plugin and provides the option to delete all it's data?`
That is practically not possible. You would need to know what options all of the plugins might add (use), check what is activated and what is there. The first part of that is not quiet possible.

**Comment by leedman** [comment]
Hi Christian,

I hear you. Thinking of it from the way I propose it surely is a difficult
assignment. However, think of it from a different angle.

In my search for solutions I also came across a developer's tool for
resetting the database. It removes all options and tables not part of the
original wordpress installation.

Now with that knowledge and the knowledge of what plugins are actually on
the server, one could reset with exceptions. No?

Lee Down

778-862-1626

_OMC Social Media Promotions_
omcsocial.com

Art Promotion Project,
*Arts, Artists, Artwork *
artsartistsartwork.com

http://www.dreamhost.com/r.cgi?391391/green.cgi?ArtsArtistsArtwork%7CHELPHOSTAAA
_Get Green Hosting by
Dreamhost_http://www.dreamhost.com/r.cgi?391391/green.cgi?ArtsArtistsArtwork%7CHELPHOSTAAA,
they are the hosting provider for Arts, Artists,
Artworkhttp://artsartistsartwork.com,
also fondly known as _AAA_ https://www.facebook.com/artsartistsartwork.
You can donate and help provide for service costs in support of the Arts
Community Worldwide. Currently hosted on a Virtual Private Server,
performance issues and slow site speed has been increasing in frequency.
VPS Cloud Hosting is an option currently being evaluated, wanting to
provide a stronger platform and faster speed to help grow the site. It
might even save us money.

**Comment by cfoellmann** [comment]
Might work. But I am afraid that I do not have the time to implement something big like that.

**Comment by leedman** [comment]
I understand. Kind of falls outside of the realm of your plugin now that
we've chewed it over. Appreciate the discussion.

Lee Down

778-862-1626

_OMC Social Media Promotions_
omcsocial.com

Art Promotion Project,
*Arts, Artists, Artwork *
artsartistsartwork.com

http://www.dreamhost.com/r.cgi?391391/green.cgi?ArtsArtistsArtwork%7CHELPHOSTAAA
_Get Green Hosting by
Dreamhost_http://www.dreamhost.com/r.cgi?391391/green.cgi?ArtsArtistsArtwork%7CHELPHOSTAAA,
they are the hosting provider for Arts, Artists,
Artworkhttp://artsartistsartwork.com,
also fondly known as _AAA_ https://www.facebook.com/artsartistsartwork.
You can donate and help provide for service costs in support of the Arts
Community Worldwide. Currently hosted on a Virtual Private Server,
performance issues and slow site speed has been increasing in frequency.
VPS Cloud Hosting is an option currently being evaluated, wanting to
provide a stronger platform and faster speed to help grow the site. It
might even save us money.

**Comment by cfoellmann** [comment]
If you know someone who wants to contribute it I am open for that :smile:

**Comment by cfoellmann** [comment]
Close for now
